### ISSUE TITLE
Fix 90%+ of the Symbols Issues

### ISSUE THREAD

**Issue by seveibar** [tscircuit/schematic-symbols#205]
https://github.com/user-attachments/assets/af8f3707-64fa-4afe-94b0-f3b2dfc0f28d

/bounty $60

**Comment by hunxjunedo** [comment]
@seveibar the generating scripts are really buggy when it comes to keeping the right file names (messing between - and _ ). What should i do ? should I do the work keeping in mind that the generating scripts will be hardly used ? And wait for the scripts to be fixed later ? Because once you are done good and clean and you generate, you find yourself standing on zero, happened many times and its really exhausting.

**Comment by hunxjunedo** [comment]
many symbols are not up-to-date with thier source svgs, what should I do in that scenario ? Like the constant-current-diode.
